language: python
python:
  - "3.6"

before_install:
  - sudo apt-get update

install:
  - pip install flask
  - pip install -r requirements.txt
  - pip install tox-travis

script:
     - flask run
     - tox
